---
- name: Deploy voucherapp in OpenShift
  hosts: all
  vars_files:
   - vars.yml
  
  tasks:

    - include_tasks: setup.yml
      tags:
        - setup
        - compile
      
    - name: login to openshit environment
      shell: "oc login --insecure-skip-tls-verify=true -u {{ username}} -p {{ password }}  {{ openshift }}"
      
    - name: create  voucher-app project 
      shell:  "oc new-project {{ project_name }}"
      register: command_result
      failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
      changed_when: "'exists' not in command_result.stderr"
      
    - name: Define OpenShift project
      shell: "oc project {{ project_name }}"
      register: command_result
   

    - name: import mongodb template 
      shell: "oc create -f {{mongo_template_path}} -n {{project_name}} "

    - name: Create MongoDB template 
      shell: "oc new-app  {{ mongo_template}}  -n {{ project_name }}"     
    
    - name: Sleep for 20 seconds until mongodb is deployed 
      wait_for:
        timeout: 20
      delegate_to: localhost

    
    - name: Deploy Backend from github repo 
      shell: "oc new-app nodejs~https://github.com/Anis-Abaza/ov-backend.git --name ov-backend  -n {{ project_name}} "
  
    - name: Deploy Socket-server from github repo
      shell: "oc new-app nodejs~https://github.com/Anis-Abaza/socket-server.git -n {{ project_name }} "

    - name: Import frontend image stream from Dockerhub
      shell: "oc import-image {{image_stream}} --confirm -n {{ project_name }}"
  
   - name: Deploy frontend using imagestream 
     shell:" ic new-app {{image_stream}} --confirm -n {{project_name}}"

