---
- name: Deploy voucherapp in OpenShift
  hosts: all
  vars_files:
   - vars.yml
  
  tasks:

    - include_tasks: setup.yml
      tags:
        - setup
        - compile
      
    - name: login to openshit environment
      shell: "oc login --insecure-skip-tls-verify=true -u {{ username}} -p {{ password }}  {{ openshift }}"
      
    - name: create  voucher-app project 
      shell:  "oc new-project {{ project_name }}"
      register: command_result
      failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
      changed_when: "'exists' not in command_result.stderr"
      
    - name: Define OpenShift project
      shell: "oc project {{ project_name }}"
      register: command_result
   

    - name: Create mongodb with 3 replica Set 
      shell: "oc new-app mongo.yml -n {{project_name}} "
      
    -  
    
    - name: Deploy Voucher_app Backend 
      shell: "oc new-app {{ backend_rep_url }} --name ov-backend  -n {{ project_name}} "
  
    - name: Expose backend service
      shell: "oc expose svc/ov-backend -n {{ project_name }} "

    - name: Deploy Socket-Server
      shell: "oc new-app {{ socket_rep_url }} --name ov-backend "
      
      
  
   - name: Deploy frontend using imagestream 
     shell:" ic new-app {{image_stream}} --confirm -n {{project_name}}"

